begin; 
    update package set state = 'to_delete' where state <> 'active';
    update package set state = 'to_delete' where owner_org is null;
    delete from resource_revision where package_id in (select id from package where state = 'to_delete' );
    delete from package_tag_revision where package_id in (select id from package where state = 'to_delete');
    delete from member_revision where table_id in (select id from package where state = 'to_delete');
    delete from package_extra_revision where package_id in (select id from package where state = 'to_delete');
    delete from package_revision where id in (select id from package where state = 'to_delete');
    delete from package_tag where package_id in (select id from package where state = 'to_delete');
    delete from resource_view where resource_id in (select id from resource where package_id in (select id from package where state = 'to_delete'));
    delete from resource where package_id in (select id from package where state = 'to_delete');
    delete from package_extra where package_id in (select id from package where state = 'to_delete');
    delete from member where table_id in (select id from package where state = 'to_delete');
    delete from harvest_object_error hoe using harvest_object ho where ho.id = hoe.harvest_object_id and package_id  in (select id from package where state = 'to_delete');
    delete from harvest_object_extra hoe using harvest_object ho where ho.id = hoe.harvest_object_id and package_id  in (select id from package where state = 'to_delete');
    delete from harvest_object where package_id in (select id from package where state = 'to_delete');
    delete from package_extent where package_id in (select id from package where state = 'to_delete');
    delete from package where id in (select id from package where state = 'to_delete'); 
commit;
